version: '3'

services:
  frontend:
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - /C_DRIVE/Users/ACER-PC/Desktop/docker/projects/realworld-docker/frontend:/usr/src/app

  api:
    command: npm run dev
    volumes:
      - /C_DRIVE/Users/ACER-PC/Desktop/docker/projects/realworld-docker/api/src:/usr/src/app/src

  auth:
    command: npm run dev
    volumes:
      - /C_DRIVE/Users/ACER-PC/Desktop/docker/projects/realworld-docker/auth/src:/usr/src/app/src

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev