version: '3'

services:
  frontend:
    build: ./frontend
    container_name: realworld-docker-frontend
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    stdin_open: true
    tty: true
    volumes:
      - /C_DRIVE/Users/ACER-PC/Desktop/docker/projects/realworld-docker/frontend:/usr/src/app

  api:
    build: ./api
    container_name: realworld-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001/tcp"
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002/tcp"
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:4.1.8-xenial
    container_name: realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:4.1.8-xenial
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:

